{% set name = "nagios" %}
{% set version = "4.4.10" %}
{% set sha256 = "8118dcfa0ce1c69506ba582c9ff0190d5b348bae0006b117eb17ada3bb5c776d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/NagiosEnterprises/nagioscore/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script:
    - ./configure --prefix $PREFIX --with-nagios-user=`whoami` --with-nagios-group=`whoami`  # [unix]
    - ./configure --prefix $PREFIX --with-nagios-user=`whoami` --with-nagios-group="staff"  # [osx]
    - make all
    - make install

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [not win]
  host:
    - openssl
    - unzip  # [unix] 
    - pkg-config  # [unix] 

test:
  commands:
    - nagios --version

about:
  home: https://github.com/NagiosEnterprises/nagioscore
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Nagios Core
  description: Nagios is a host/service/network monitoring program written in C and released under the GNU General Public License, version 2.
  doc_url: https://www.nagios.org
  dev_url: https://github.com/NagiosEnterprises/nagioscore

extra:
  recipe-maintainers:
    - timkpaine
